-- Lab 5: Truy vấn lồng nâng cao
USE SCHOOL_MANAGEMENT

------------------------------------------------------------------------------------
-- Mỗi câu truy vấn, viết theo 3 cách lần lượt sử dụng EXCEPT, NOT EXISTS và COUNT

-- Q58. Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề
-- Xem thông tin các bảng 
SELECT *
FROM CONGVIEC

SELECT *
FROM CHUDE

SELECT *
FROM DETAI

SELECT *
FROM THAMGIADT

-- Update dữ liệu để test:
INSERT INTO CONGVIEC VALUES ('005', 1, N'Xác định yêu cầu', '2008-03-10', '2009-02-05')
INSERT INTO CONGVIEC VALUES ('003', 1, N'Xác định yêu cầu', '2008-06-10', '2009-04-05')

INSERT INTO THAMGIADT VALUES ('003', '005', 1, 1, N'Đạt') 
INSERT INTO THAMGIADT VALUES ('003', '003', 1, 1, NULL)

-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV 
AND NOT EXISTS ( (SELECT DT1.MACD
				  FROM CHUDE AS CD1, DETAI AS DT1
				  WHERE CD1.MACD = DT1.MACD)
				  EXCEPT
                 (SELECT DT2.MACD
				  FROM THAMGIADT AS TGDT2, DETAI AS DT2
				  WHERE TGDT2.MADT = DT2.MADT AND TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS 
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS ( SELECT *
				 FROM CHUDE AS CD
				 WHERE NOT EXISTS (SELECT *
								   FROM THAMGIADT AS TGDT2, DETAI AS DT
								   WHERE TGDT1.MAGV = TGDT2.MAGV 
								   AND DT.MADT = TGDT2.MADT AND CD.MACD = DT.MACD) )

-- Gom nhóm 
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, DETAI AS DT, CHUDE AS CD
WHERE GV.MAGV = TGDT.MAGV AND DT.MADT = TGDT.MADT 
AND CD.MACD = DT.MACD AND GV.MAGV IN (SELECT MAGV FROM THAMGIADT)
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MACD) = (SELECT COUNT(DISTINCT CD.MACD)
								  FROM CHUDE AS CD)

-- Q59. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn HTTT tham gia
-- Check dữ liệu: 
SELECT *
FROM GIAOVIEN 

SELECT *
FROM THAMGIADT
-- EXCEPT
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS ( (SELECT GV.MAGV
                  FROM GIAOVIEN AS GV
				  WHERE GV.MABM = 'HTTT')
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MAGV
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MADT= TGDT2.MADT) )

-- NOT EXISTS
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS (SELECT *
				FROM GIAOVIEN AS GV
				WHERE GV.MABM = 'HTTT'
				AND NOT EXISTS ( SELECT *
								 FROM THAMGIADT AS TGDT2
								 WHERE TGDT1.MADT = TGDT2.MADT 
								 AND GV.MAGV = TGDT2.MAGV) )

-- Gom nhóm
SELECT DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT, GIAOVIEN AS GV
WHERE DT.MADT = TGDT.MADT AND TGDT.MAGV = GV.MAGV AND GV.MABM = 'HTTT'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(DISTINCT MAGV)
								  FROM GIAOVIEN 
								  WHERE MABM = 'HTTT')

-- Q60. Cho biết tên đề tài có tất cả giảng viên bộ môn 'Hệ thống thông tin' tham gia
-- EXCEPT
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT 
AND NOT EXISTS ( (SELECT GV.MAGV
				  FROM GIAOVIEN AS GV, BOMON AS BM
				  WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin')
				  EXCEPT 
				 (SELECT TGDT2.MAGV
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MADT = TGDT2.MADT) )

-- NOT EXISTS
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS ( SELECT *
				 FROM GIAOVIEN AS GV, BOMON AS BM
				 WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
				 AND NOT EXISTS (SELECT * 
								 FROM THAMGIADT AS TGDT2
								 WHERE GV.MAGV = TGDT2.MAGV
								 AND TGDT1.MADT = TGDT2.MADT) )

-- Gom nhóm 
SELECT DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT, GIAOVIEN AS GV, BOMON AS BM
WHERE DT.MADT = TGDT.MADT AND GV.MAGV = TGDT.MAGV 
AND GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(GV.MAGV)
                                  FROM GIAOVIEN AS GV, BOMON AS BM
								  WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin')

-- Q61. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD 
-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM THAMGIADT AS TGDT1, GIAOVIEN AS GV
WHERE  GV.MAGV = TGDT1.MAGV 
AND NOT EXISTS ( (SELECT DISTINCT DT.MADT
				  FROM DETAI AS DT 
				  WHERE DT.MACD = 'QLGD')
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MADT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )
				
-- NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS ( SELECT * 
				 FROM DETAI AS DT
				 WHERE DT.MACD = 'QLGD'
				 AND NOT EXISTS ( SELECT *
								  FROM THAMGIADT AS TGDT2
								  WHERE TGDT1.MAGV = TGDT2.MAGV
								  AND TGDT2.MADT = DT.MADT) )

-- Gom nhóm:
SELECT GV.HOTEN 
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, DETAI AS DT
WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT 
AND DT.MACD = 'QLGD'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(DISTINCT MADT)
								  FROM DETAI 
								  WHERE MACD = 'QLGD')

-- Q62. Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã tham gia
-- Xem thông tin các bảng:
SELECT *
FROM GIAOVIEN 

SELECT *
FROM THAMGIADT

-- Update dữ liệu:
INSERT INTO THAMGIADT VALUES ('001', '001', 1, 2, NULL)

-- EXCEPT
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV AND GV.HOTEN != N'Trần Trà Hương'
AND NOT EXISTS ( (SELECT DISTINCT TTH_TGDT.MADT
				  FROM GIAOVIEN AS TTH, THAMGIADT AS TTH_TGDT
				  WHERE TTH.MAGV = TTH_TGDT.MAGV 
				  AND TTH.HOTEN = N'Trần Trà Hương') 
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MADT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV AND GV.HOTEN != N'Trần Trà Hương'
AND NOT EXISTS   (SELECT * 
				  FROM GIAOVIEN AS TTH, THAMGIADT AS TTH_TGDT
				  WHERE TTH.MAGV = TTH_TGDT.MAGV 
				  AND TTH.HOTEN = N'Trần Trà Hương'
				  AND NOT EXISTS (SELECT *
								  FROM THAMGIADT AS TGDT2
								  WHERE TGDT1.MAGV = TGDT2.MAGV 
								  AND TGDT2.MADT = TTH_TGDT.MADT) )

-- Gom nhóm 
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, GIAOVIEN AS TTH, THAMGIADT AS TTH_TGDT
WHERE GV.MAGV = TGDT.MAGV AND GV.HOTEN != N'Trần Trà Hương'  
AND (TGDT.MADT IN (SELECT DISTINCT TTH_TGDT.MADT
				   FROM GIAOVIEN AS TTH, THAMGIADT AS TTH_TGDT
				   WHERE TTH.MAGV = TTH_TGDT.MAGV 
				   AND TTH.HOTEN = N'Trần Trà Hương'))
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TGDT.MADT) = (SELECT COUNT(DISTINCT TTH_TGDT.MADT)
									FROM GIAOVIEN AS TTH, THAMGIADT AS TTH_TGDT
									WHERE TTH.MAGV = TTH_TGDT.MAGV 
									AND TTH.HOTEN = N'Trần Trà Hương')

-- Q63. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa hữu cơ tham gia
-- (Sửa đề từ 'Hóa hữu cơ' thành 'Vi sinh' để kiểm tra được rõ đáp án hơn)
-- Xem thông tin các bảng:
SELECT *
FROM BOMON

SELECT *
FROM GIAOVIEN

SELECT *
FROM THAMGIADT

-- EXCEPT: 
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS ( (SELECT DISTINCT GV.MAGV
				  FROM GIAOVIEN AS GV, BOMON AS BM
				  WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Vi sinh')
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MAGV
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MADT = TGDT2.MADT ) )

-- NOT EXISTS:
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS (SELECT *
				FROM GIAOVIEN AS GV, BOMON AS BM
				WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Vi sinh'
				AND NOT EXISTS (SELECT *
								FROM THAMGIADT AS TGDT2
								WHERE TGDT1.MADT = TGDT2.MADT
								AND GV.MAGV = TGDT2.MAGV) )

-- Gom nhóm:
SELECT DT.MADT, DT.TENDT
FROM DETAI AS DT, GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
WHERE DT.MADT = TGDT.MADT AND GV.MAGV = TGDT.MAGV 
AND GV.MABM = BM.MABM AND BM.TENBM = N'Vi sinh'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(DISTINCT GV.MAGV)
							      FROM GIAOVIEN AS GV, BOMON AS BM
				                  WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Vi sinh')

-- Q64. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006
-- Xem thông tin các bảng:
SELECT *
FROM CONGVIEC

SELECT *
FROM THAMGIADT

-- EXCEPT:
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE TGDT1.MAGV = GV.MAGV
AND NOT EXISTS ( (SELECT DISTINCT CV.MADT, CV.STT
                  FROM CONGVIEC AS CV
				  WHERE CV.MADT = '006')
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MADT, TGDT2.STT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS (SELECT *
				FROM CONGVIEC AS CV
				WHERE CV.MADT = '006'
				AND NOT EXISTS (SELECT *
								FROM THAMGIADT AS TGDT2
								WHERE TGDT1.MAGV = TGDT2.MAGV
								AND TGDT2.STT = CV.STT
								AND TGDT2.MADT = CV.MADT) )

-- Gom nhóm: 
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, CONGVIEC AS CV
WHERE GV.MAGV = TGDT.MAGV AND CV.MADT = TGDT.MADT
AND CV.MADT = '006' AND TGDT.STT = CV.STT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT CV.STT) = (SELECT COUNT(DISTINCT STT)
								 FROM CONGVIEC
								 WHERE MADT = '006') 

-- Q65. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng dụng công nghệ
-- Xem thông tin các bảng:
SELECT *
FROM DETAI

SELECT *
FROM THAMGIADT

-- EXCEPT 
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS ( (SELECT DISTINCT DT.MADT
				  FROM DETAI AS DT, CHUDE AS CD
				  WHERE DT.MACD = CD.MACD 
				  AND CD.TENCD = N'Ứng dụng công nghệ')
				  EXCEPT 
				 (SELECT TGDT2.MADT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS 
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS (  SELECT *
				  FROM DETAI AS DT, CHUDE AS CD
				  WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Ứng dụng công nghệ'
				  AND NOT EXISTS (SELECT *
								  FROM THAMGIADT AS TGDT2
								  WHERE TGDT1.MAGV = TGDT2.MAGV 
								  AND DT.MADT = TGDT2.MADT) )

-- Gom nhóm: 
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, DETAI AS DT, CHUDE AS CD
WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT
AND DT.MACD = CD.MACD AND CD.TENCD = N'Ứng dụng công nghệ'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(DISTINCT DT.MADT)
								  FROM DETAI AS DT, CHUDE AS CD
								  WHERE DT.MACD = CD.MACD
								  AND CD.TENCD = N'Ứng dụng công nghệ')

-- Q66. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài do Trần Trà Hương 
-- làm chủ nhiệm.
-- Xem thông tin các bảng:
SELECT DISTINCT GV.MAGV, DT.*
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE GV.HOTEN = N'Trần Trà Hương' 
AND GV.MAGV = DT.GVCNDT

SELECT *
FROM THAMGIADT

-- Update dữ liệu để test:
INSERT INTO THAMGIADT VALUES ('009', '001', 1, 1, NULL)

-- EXCEPT:
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS ( (SELECT DISTINCT DT.MADT
				  FROM GIAOVIEN AS TTH, DETAI AS DT
				  WHERE TTH.MAGV = DT.GVCNDT 
				  AND TTH.HOTEN = N'Trần Trà Hương')
				  EXCEPT
				 (SELECT TGDT2.MADT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS 
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS (SELECT *
				FROM GIAOVIEN AS TTH, DETAI AS DT
				WHERE TTH.HOTEN = N'Trần Trà Hương'
				AND TTH.MAGV = DT.GVCNDT 
				AND NOT EXISTS (SELECT *
								FROM THAMGIADT AS TGDT2
								WHERE TGDT1.MAGV = TGDT2.MAGV
								AND TGDT2.MADT = DT.MADT) )

-- Q67. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia
-- Xem thông tin các bảng:
SELECT GV.*
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT'

SELECT *
FROM THAMGIADT

-- Update dữ liệu để test
INSERT INTO THAMGIADT VALUES ('011', '001', 1, 1.5, NULL)

-- EXCEPT 
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS ( (SELECT DISTINCT GV.MAGV
				  FROM GIAOVIEN AS GV, BOMON AS BM
				  WHERE GV.MABM = BM.MABM
				  AND BM.MAKHOA = 'CNTT')
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MAGV
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MADT = TGDT2.MADT) )

-- NOT EXISTS 
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS ( SELECT *
				 FROM GIAOVIEN AS GV, BOMON AS BM
				 WHERE GV.MABM = BM.MABM 
				 AND BM.MAKHOA = 'CNTT' 
				 AND NOT EXISTS ( SELECT *
								  FROM THAMGIADT AS TGDT2
								  WHERE TGDT1.MADT = TGDT2.MADT
								  AND TGDT2.MAGV = GV.MAGV) )

-- Gom nhóm
SELECT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT, GIAOVIEN AS GV, BOMON AS BM
WHERE DT.MADT = TGDT.MADT AND GV.MAGV = TGDT.MAGV
AND BM.MABM = GV.MABM AND BM.MAKHOA = 'CNTT'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(DISTINCT GV.MAGV)
								  FROM GIAOVIEN AS GV, BOMON AS BM
								  WHERE GV.MABM = BM.MABM
								  AND BM.MAKHOA = 'CNTT') 

-- Q68. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 
-- 'Nghiên cứu tế bào gốc'
-- Xem thông tin các bảng:
SELECT CV.*
FROM CONGVIEC AS CV, DETAI AS DT
WHERE CV.MADT = DT.MADT
AND DT.TENDT = N'Nghiên cứu tế bào gốc'

SELECT *
FROM THAMGIADT

-- EXCEPT
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS ( (SELECT DISTINCT CV.MADT, CV.STT
			      FROM CONGVIEC AS CV, DETAI AS DT
				  WHERE CV.MADT = DT.MADT
				  AND DT.TENDT = N'Nghiên cứu tế bào gốc')
				  EXCEPT 
				 (SELECT DISTINCT TGDT2.MADT, TGDT2.STT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS (SELECT *
			    FROM CONGVIEC AS CV, DETAI AS DT
				WHERE CV.MADT = DT.MADT
				AND DT.TENDT = N'Nghiên cứu tế bào gốc'
				AND NOT EXISTS (SELECT *
								FROM THAMGIADT AS TGDT2
						        WHERE TGDT1.MAGV = TGDT2.MAGV
								AND TGDT2.MADT = CV.MADT
								AND TGDT2.STT = CV.STT) )

-- Gom nhóm:
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, CONGVIEC AS CV, DETAI AS DT
WHERE GV.MAGV = TGDT.MAGV AND CV.MADT = TGDT.MADT AND CV.STT = TGDT.STT
AND DT.MADT = TGDT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT CV.STT) = (SELECT COUNT(DISTINCT CV.STT)
                                          FROM CONGVIEC AS CV, DETAI AS DT
										  WHERE CV.MADT = DT.MADT
										  AND DT.TENDT = N'Nghiên cứu tế bào gốc') 

-- Q69. Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu
-- Sửa đề thành 300 :)))
-- Xem thông tin các bảng:
SELECT *
FROM DETAI

SELECT *
FROM THAMGIADT
			   
-- Update dữ liệu để test:
INSERT INTO THAMGIADT VALUES ('006', '003', 1, 1, NULL)

-- EXCEPT:
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV 
AND NOT EXISTS ( (SELECT DISTINCT DT.MADT
				  FROM DETAI AS DT
				  WHERE DT.KINHPHI >= 300)
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MADT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS 
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS (SELECT *
				FROM DETAI AS DT
				WHERE DT.KINHPHI >= 300
				AND NOT EXISTS (SELECT *
								FROM THAMGIADT AS TGDT2
								WHERE TGDT1.MAGV = TGDT2.MAGV
								AND TGDT2.MADT = DT.MADT) )

-- Gom nhóm:
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, DETAI AS DT
WHERE GV.MAGV = TGDT.MAGV AND DT.MADT = TGDT.MADT
AND DT.KINHPHI >= 300
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(DISTINCT DT.MADT) 
								  FROM DETAI AS DT
								  WHERE DT.KINHPHI >= 300)

-- Q70. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia
-- Xem thông tin các bảng:
SELECT GV.*
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA
AND K.TENKHOA = N'Sinh học'

SELECT *
FROM THAMGIADT

-- EXCEPT: 
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS ( (SELECT DISTINCT GV.MAGV
				  FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
				  WHERE GV.MABM = BM.MABM AND K.MAKHOA = BM.MAKHOA
				  AND K.TENKHOA = N'Sinh học')
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MAGV
				  FROM THAMGIADT AS TGDT2 
				  WHERE TGDT1.MADT = TGDT2.MADT) ) 

-- NOT EXISTS 
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT1
WHERE DT.MADT = TGDT1.MADT
AND NOT EXISTS (SELECT *
				FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
				WHERE GV.MABM = BM.MABM 
				AND K.MAKHOA = BM.MAKHOA AND K.TENKHOA = N'Sinh học'
				AND NOT EXISTS (SELECT *
								FROM THAMGIADT AS TGDT2
								WHERE TGDT1.MADT = TGDT2.MADT
								AND TGDT2.MAGV = GV.MAGV) )

-- Gom nhóm:
SELECT DT.MADT, DT.TENDT
FROM DETAI AS DT, THAMGIADT AS TGDT, GIAOVIEN AS GV, 
BOMON AS BM, KHOA AS K
WHERE DT.MADT = TGDT.MADT AND GV.MAGV = TGDT.MAGV
AND GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA
AND K.TENKHOA = N'Sinh học'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(DISTINCT GV.MAGV)
								  FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
								  WHERE GV.MABM = BM.MABM AND K.MAKHOA = BM.MAKHOA
								  AND K.TENKHOA = N'Sinh học')


-- Q71. Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả 
-- các công việc của đề tài "Ứng dụng hóa học xanh"
-- Xem thông tin các bảng:
SELECT CV.*
FROM CONGVIEC AS CV, DETAI AS DT
WHERE DT.MADT = CV.MADT AND DT.TENDT = N'Ứng dụng hóa học xanh'

SELECT *
FROM THAMGIADT

-- Update dữ liệu để test:
INSERT INTO THAMGIADT VALUES ('005', '005', 1, 1.5, NULL)

-- EXCEPT:
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGAYSINH
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS ( (SELECT DISTINCT CV.MADT, CV.STT
				  FROM CONGVIEC AS CV, DETAI AS DT
				  WHERE CV.MADT = DT.MADT 
				  AND DT.TENDT = N'Ứng dụng hóa học xanh')
				  EXCEPT 
				 (SELECT DISTINCT TGDT2.MADT, TGDT2.STT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS 
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGAYSINH
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV
AND NOT EXISTS (SELECT *
				FROM CONGVIEC AS CV, DETAI AS DT
				WHERE CV.MADT = DT.MADT
				AND DT.TENDT = N'Ứng dụng hóa học xanh'
				AND NOT EXISTS (SELECT *
							    FROM THAMGIADT AS TGDT2
								WHERE TGDT1.MAGV = TGDT2.MAGV
								AND TGDT2.MADT = CV.MADT
								AND TGDT2.STT = CV.STT) )

-- Gom nhóm:
SELECT GV.MAGV, GV.HOTEN, GV.NGAYSINH
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, CONGVIEC AS CV, DETAI AS DT
WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = CV.MADT
AND TGDT.STT = CV.STT AND DT.MADT = CV.MADT
AND DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV, GV.HOTEN, GV.NGAYSINH
HAVING COUNT(DISTINCT CV.STT) = (SELECT COUNT(DISTINCT CV.STT)
								 FROM CONGVIEC AS CV, DETAI AS DT
								 WHERE DT.MADT = CV.MADT 
								 AND DT.TENDT = N'Ứng dụng hóa học xanh')

-- Q72. Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên
-- tham gia tất cả các đề tài thuộc chủ đề "Nghiên cứu phát triển"
-- Xem thông tin các bảng:
SELECT *
FROM CONGVIEC

SELECT DT.*
FROM DETAI AS DT, CHUDE AS CD
WHERE DT.MACD = CD.MACD
AND CD.TENCD = N'Nghiên cứu phát triển'

SELECT *
FROM THAMGIADT

-- Update dữ liệu để test
INSERT INTO CONGVIEC VALUES ('004', 1, N'Xác định yêu cầu', '2007-05-04', '2008-03-02')
INSERT INTO THAMGIADT VALUES ('006', '004', 1, 1, NULL)

-- EXCEPT
SELECT DISTINCT GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN
FROM GIAOVIEN AS GV,BOMON AS BM, GIAOVIEN AS NQL, THAMGIADT AS TGDT1
WHERE GV.MAGV = TGDT1.MAGV AND GV.MABM = BM.MABM AND GV.GVQLCM = NQL.MAGV 
AND NOT EXISTS ( (SELECT DISTINCT DT.MADT
                  FROM DETAI AS DT, CHUDE AS CD
				  WHERE DT.MACD = CD.MACD
				  AND CD.TENCD = N'Nghiên cứu phát triển')
				  EXCEPT
				 (SELECT DISTINCT TGDT2.MADT
				  FROM THAMGIADT AS TGDT2
				  WHERE TGDT1.MAGV = TGDT2.MAGV) )

-- NOT EXISTS 
SELECT DISTINCT GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, GIAOVIEN AS NQL, THAMGIADT AS TGDT1
WHERE GV.MABM = BM.MABM AND GV.GVQLCM = NQL.MAGV 
AND GV.MAGV = TGDT1.MAGV
AND NOT EXISTS (SELECT *
				FROM DETAI AS DT, CHUDE AS CD
				WHERE DT.MACD = CD.MACD
				AND CD.TENCD = N'Nghiên cứu phát triển'
				AND NOT EXISTS (SELECT *
								FROM THAMGIADT AS TGDT2
								WHERE TGDT2.MAGV = TGDT1.MAGV
								AND TGDT2.MADT = DT.MADT) )

-- Gom nhóm:
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, GIAOVIEN AS NQL, 
THAMGIADT AS TGDT, DETAI AS DT, CHUDE AS CD
WHERE GV.MAGV = TGDT.MAGV AND GV.MABM = BM.MABM
AND GV.GVQLCM = NQL.MAGV AND DT.MADT = TGDT.MADT
AND DT.MACD = CD.MACD AND CD.TENCD = N'Nghiên cứu phát triển'
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(DISTINCT DT.MADT)
								  FROM DETAI AS DT, CHUDE AS CD
								  WHERE DT.MACD = CD.MACD
								  AND CD.TENCD = N'Nghiên cứu phát triển')

---------------------------------- END ----------------------------------